# Generated by Django 4.0.1 on 2022-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
