# Generated by Django 4.0.1 on 2022-01-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
