# Generated by Django 4.0.1 on 2022-02-05 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockar', '0002_storageoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageoffer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
