# Generated by Django 4.0.1 on 2022-02-05 16:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockar', '0003_alter_storageoffer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageoffer',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
